theme: minima
title: Hakoniwa Explorer Plus Guide
author: TibyAndy
description: Hakoniwa Explorer Plus Guide
markdown: GFM
plugins:
 - jemoji
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
header_pages:
 - index.md
