theme: minima
title: Hakoniwa Explorer Plus Guide
author: TibyAndy
description: All this guide content is licensed under CC BY-SA 4.0
markdown: kramdown #GFM
plugins:
  - jemoji
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false
header_pages:
 - index.md
twitter_username: tibyandy
github_username: tibyandy